# Form implementation generated from reading ui file 'd:\Programming\Python\Calculator\UI\About.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(351, 300)
        Dialog.setMinimumSize(QtCore.QSize(351, 300))
        Dialog.setMaximumSize(QtCore.QSize(351, 300))
        self.label_about = QtWidgets.QLabel(Dialog)
        self.label_about.setGeometry(QtCore.QRect(0, 10, 351, 300))
        self.label_about.setMinimumSize(QtCore.QSize(351, 300))
        self.label_about.setMaximumSize(QtCore.QSize(351, 300))
        self.label_about.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_about.setObjectName("label_about")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "About Information"))
        self.label_about.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Python Portfolio Project by Macarius D. Auguste<br/></span></p><p align=\"center\"><span style=\" font-weight:600;\">About</span></p><p align=\"center\"><br/><span style=\" font-weight:600;\">Basic Calculator created using:</span></p><p align=\"center\">Python 3.10</p><p align=\"center\">PyQT6</p></body></html>"))
